#!/usr/bin/env bash
# Install the agent config onto this machine. Idempotent — safe to re-run.
#
# Layers: this repo is the portable method layer. If ~/agents-cfg-private (or
# $PRIVATE_CONFIG) exists it is layered on top. At a new job, clone only this
# repo and the workflows stay identical minus the employer specifics.
set -euo pipefail

for c in git python3; do
  command -v "$c" >/dev/null || { echo "missing prerequisite: $c" >&2; exit 1; }
done
case "$(uname -s)" in Linux|Darwin) ;; *) echo "unsupported OS: $(uname -s)" >&2; exit 1;; esac

AC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRIVATE="${PRIVATE_CONFIG:-$HOME/agents-cfg-private}"
CLAUDE_DIR="$HOME/.claude"
BIN="$HOME/.local/bin"
mkdir -p "$CLAUDE_DIR"/{skills,agents,hooks} "$BIN"

link() { # link <target> <linkname>
  [ -e "$1" ] || return 0
  if [ -L "$2" ] || [ ! -e "$2" ]; then ln -sfn "$1" "$2"
  else echo "  ! not a symlink, leaving alone: $2"; fi
}

echo "== skills"
# Third-party skills stay installer-managed in ~/.agents/skills so that
# `npx skills update` keeps them fresh. We only link them into place — vendoring
# them would freeze them at one commit and cut them off from upstream.
# The `skills` CLI reads skills-lock.json from the CURRENT directory and installs
# into ./.agents/skills — so running it from $HOME targets ~/.agents/skills.
link "$AC/skills-lock.json" "$HOME/skills-lock.json"
if [ -d "$HOME/.agents/skills" ]; then
  for d in "$HOME"/.agents/skills/*/; do link "${d%/}" "$CLAUDE_DIR/skills/$(basename "$d")"; done
else
  echo "  ! ~/.agents/skills is missing — run:  cd ~ && npx skills experimental_install"
fi
# Repo-owned skills last, so they win on a name clash.
for d in "$AC"/skills/*/; do link "${d%/}" "$CLAUDE_DIR/skills/$(basename "$d")"; done
[ -d "$PRIVATE/skills" ] && for d in "$PRIVATE"/skills/*/; do link "${d%/}" "$CLAUDE_DIR/skills/$(basename "$d")"; done

echo "== agents / hooks"
for f in "$AC"/agents/*.md;  do link "$f" "$CLAUDE_DIR/agents/$(basename "$f")"; done
for f in "$AC"/hooks/*;      do link "$f" "$CLAUDE_DIR/hooks/$(basename "$f")"; done

echo "== bin"
for f in "$AC"/bin/*;        do link "$f" "$BIN/$(basename "$f")"; done
[ -d "$PRIVATE/bin" ] && for f in "$PRIVATE"/bin/*; do link "$f" "$BIN/$(basename "$f")"; done

echo "== instruction files"
# Claude reads CLAUDE.md and expands @imports natively, so edits are live.
link "$AC/conventions/AGENTS.md" "$CLAUDE_DIR/AGENTS.portable.md"
: > "$CLAUDE_DIR/CLAUDE.md.tmp"
echo "@AGENTS.portable.md" >> "$CLAUDE_DIR/CLAUDE.md.tmp"
if [ -f "$PRIVATE/AGENTS.md" ]; then
  link "$PRIVATE/AGENTS.md" "$CLAUDE_DIR/AGENTS.private.md"
  echo "@AGENTS.private.md" >> "$CLAUDE_DIR/CLAUDE.md.tmp"
fi
mv -f "$CLAUDE_DIR/CLAUDE.md.tmp" "$CLAUDE_DIR/CLAUDE.md"

# Codex reads AGENTS.md. Concatenate rather than rely on @import support.
{ echo "<!-- GENERATED by agent-config/install.sh — edit the source repos, then re-run -->"; echo
  cat "$AC/conventions/AGENTS.md"
  [ -f "$PRIVATE/AGENTS.md" ] && { echo; cat "$PRIVATE/AGENTS.md"; }
} > "$HOME/AGENTS.md"
mkdir -p "$HOME/.codex"; link "$HOME/AGENTS.md" "$HOME/.codex/AGENTS.md"

echo "== mcp servers (keys from env; nothing secret is stored in this repo)"
if command -v claude >/dev/null && [ -f "$AC/mcp/servers.json" ]; then
  python3 - "$AC/mcp/servers.json" <<'PY'
import json,os,subprocess,sys
for s in json.load(open(sys.argv[1]))["servers"]:
    name,url = s["name"], s["url"]
    env = s.get("header_env")
    if env and not os.environ.get(env):
        print(f"  skip {name}: ${env} not set"); continue
    cmd=["claude","mcp","add","--scope","user","--transport","http",name,url]
    if env: cmd += ["--header", f"{s['header_name']}: {os.environ[env]}"]
    r=subprocess.run(cmd,capture_output=True,text=True)
    print(f"  {'ok' if r.returncode==0 else 'exists/failed'} {name}")
PY
fi

echo "== done. settings/settings.template.json is a starting point; merge by hand."
