#!/usr/bin/env python3
"""Safely update impstack-owned harness instruction files."""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import os
import pathlib
import re
import sys
import tempfile
from dataclasses import dataclass

MAX_BACKUPS = 5


@dataclass(frozen=True)
class Plan:
    key: str
    path: pathlib.Path
    desired: bytes
    action: str
    existing: bytes | None


def rendered(body: bytes) -> bytes:
    digest = hashlib.sha256(body).hexdigest()
    return f"<!-- impstack-managed: instructions sha256={digest} -->\n".encode() + body


def file_digest(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def classify(key: str, path: pathlib.Path, desired: bytes, legacy: bytes, recorded: str | None) -> Plan:
    if not path.exists():
        return Plan(key, path, desired, "replace", None)
    existing = path.read_bytes()
    if recorded == file_digest(existing):
        action = "noop" if existing == desired else "replace"
        return Plan(key, path, desired, action, existing)
    if existing == legacy:
        return Plan(key, path, desired, "replace", existing)
    return Plan(key, path, desired, "conflict", existing)


def load_state(path: pathlib.Path) -> dict[str, str]:
    if not path.exists():
        return {}
    raw = json.loads(path.read_text())
    if raw.get("version") != 1 or not isinstance(raw.get("targets"), dict):
        raise ValueError(f"invalid instruction state: {path}")
    targets = raw["targets"]
    if not all(isinstance(key, str) and re.fullmatch(r"[0-9a-f]{64}", value) for key, value in targets.items()):
        raise ValueError(f"invalid instruction state: {path}")
    return targets


def write_state(path: pathlib.Path, targets: dict[str, str]) -> None:
    content = json.dumps({"version": 1, "targets": dict(sorted(targets.items()))}, indent=2) + "\n"
    replace(path, content.encode())


def backup(path: pathlib.Path, content: bytes) -> pathlib.Path:
    digest = hashlib.sha256(content).hexdigest()[:12]
    base = path.with_name(f"{path.name}.impstack-backup.{digest}")
    candidate = base
    counter = 1
    while candidate.exists():
        candidate = pathlib.Path(f"{base}.{counter}")
        counter += 1
    candidate.write_bytes(content)
    older_backups = sorted(
        (item for item in path.parent.glob(f"{path.name}.impstack-backup.*") if item != candidate),
        key=lambda item: (item.stat().st_mtime_ns, item.name),
    )
    excess = max(0, len(older_backups) + 1 - MAX_BACKUPS)
    for expired in older_backups[:excess]:
        expired.unlink()
        print(f"removed old backup: {expired}")
    return candidate


def show_diff(path: pathlib.Path, existing: bytes, desired: bytes) -> None:
    before = existing.decode(errors="replace").splitlines(keepends=True)
    after = desired.decode(errors="replace").splitlines(keepends=True)
    sys.stdout.writelines(
        difflib.unified_diff(before, after, fromfile=f"existing:{path}", tofile=f"generated:{path}", n=2)
    )


def replace(path: pathlib.Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=path.parent, prefix=f".{path.name}.", delete=False) as output:
        temporary = pathlib.Path(output.name)
        output.write(content)
    os.replace(temporary, path)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=pathlib.Path, required=True)
    parser.add_argument("--home", type=pathlib.Path, required=True)
    parser.add_argument("--private", type=pathlib.Path, required=True)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args(argv)
    state_root = pathlib.Path(os.environ.get("XDG_STATE_HOME", args.home / ".local/state"))
    state_path = state_root.expanduser().resolve() / "impstack" / "instructions.json"
    recorded = load_state(state_path)

    private_exists = (args.private / "AGENTS.md").is_file()
    claude_body = b"@AGENTS.portable.md\n" + (b"@AGENTS.private.md\n" if private_exists else b"")
    codex_parts = [(args.root / "conventions/AGENTS.md").read_bytes()]
    if private_exists:
        codex_parts.append((args.private / "AGENTS.md").read_bytes())
    codex_parts.append((args.root / "configs/pstack-codex.md").read_bytes())
    codex_body = b"\n\n".join(part.rstrip(b"\n") for part in codex_parts) + b"\n"
    old_codex = (
        "<!-- GENERATED by impstack/install.sh — edit the source repos, then re-run -->\n\n".encode()
        + codex_body
    )

    plans = (
        classify(
            ".claude/CLAUDE.md",
            args.home / ".claude/CLAUDE.md",
            rendered(claude_body),
            claude_body,
            recorded.get(".claude/CLAUDE.md"),
        ),
        classify(
            "AGENTS.md",
            args.home / "AGENTS.md",
            rendered(codex_body),
            old_codex,
            recorded.get("AGENTS.md"),
        ),
    )
    conflicts = [plan for plan in plans if plan.action == "conflict"]
    for plan in conflicts:
        assert plan.existing is not None
        saved = backup(plan.path, plan.existing)
        print(f"backup: {saved}")
        show_diff(plan.path, plan.existing, plan.desired)
    if conflicts and not args.force:
        print("instruction files differ; examine the backups and diff, then use --force", file=sys.stderr)
        return 1
    for plan in plans:
        if plan.action != "noop":
            replace(plan.path, plan.desired)
            print(f"managed: {plan.path}")
        recorded[plan.key] = file_digest(plan.desired)
    write_state(state_path, recorded)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
